# Site
title:          Hank
bio:            'It my personal websit'
description:    "Simple Jekyll theme for your blog by Taylan Tatlı"
picture:        'assets/img/myphoto.jpg'
locale:         en_US
url:            http://bighanksmallhank.github.io

# Jekyll
permalink:      /:title/
markdown:       kramdown
highlighter:    rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed


# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
